name: talk
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_facebook_auth: ^3.5.0+1

dev_dependencies:
  flutter_test:
        sdk: flutter
    # tab_indicator_styler: ^2.0.0-null-safety
  # font_awesome_flutter: ^9.0.0
  lottie: ^1.0.1
  # hexcolor: ^2.0.3
  firebase_storage: ^9.0.0
  # story_view: ^0.13.1
  # get: ^4.1.4
  # timeago: ^3.0.2
  # mime: ^1.0.0
  # hive_generator: ^1.1.0
  timeago: ^3.1.0

  # theme & ui
  adaptive_theme: ^2.2.0
  sticky_headers: ^0.2.0
  flutter_speed_dial: ^3.0.5
  emoji_picker_flutter: ^1.0.6
  flutter_keyboard_visibility: ^5.0.2
  font_awesome_flutter: ^9.1.0
  story_view: ^0.13.1
  like_button: ^2.0.2

  # adaptive_theme: ^2.2.0
  # sticky_headers: ^0.2.0

  # build_runner: ^2.0.4
  # group_button: ^2.1.2
  # story: ^0.5.1
  # shimmer: ^2.0.0
  # flutter_share: ^2.0.0

  video_trimmer: ^0.5.2

  # navigation bar
  curved_navigation_bar: ^1.0.1

  # http calls
  # http: ^0.12.0

  http: ^0.13.0

  # network
  internet_connection_checker: ^0.0.1+1

  # caching
  shared_preferences: ^2.0.6

  uuid: ^3.0.4


  # equitable
  equatable: ^2.0.3

  # Notifications

  # database & caching
  cached_network_image: ^3.1.0


  # multimedia packages
  video_player: ^2.1.10
  image_picker: ^0.7.5+2
  file_picker: ^3.0.3
  giphy_get: ^2.0.2
  # flutter_svg: ^0.22.0
  # video_trimmer: ^0.5.1

  # db packages
  cloud_firestore: ^2.3.0

  # state management
  provider: ^5.0.0

  # auth packages
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  google_sign_in: ^5.0.3
  # flutter_facebook_auth: ^3.5.0

  # fonts
  google_fonts: ^2.1.0



flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/